import { Tour, Testimonial } from '@/types'

export const tours: Tour[] = [
  {
    id: '1',
    name: 'Baku Old City Walking Tour',
    slug: 'baku-old-city',
    description: 'Explore the ancient heart of Baku, a UNESCO World Heritage Site. Wander through narrow cobblestone streets, visit the iconic Maiden Tower, discover the Shirvanshahs Palace, and experience centuries of Azerbaijani history come alive through our expert guides.',
    short_description: 'Discover UNESCO World Heritage sites in the ancient heart of Baku.',
    price: 0,
    duration: '4 hours',
    difficulty: 'Easy',
    category: 'cultural',
    region: 'Baku',
    image_url: '../img/portfolio/Oldtown1.jpg',
    gallery: ['../img/portfolio/Oldtown1.jpg', '../img/portfolio/old town 2.jpg'],
    highlights: ['Maiden Tower', 'Shirvanshahs Palace', 'Traditional carpet shops', 'Local artisan workshops'],
    included: ['Professional guide', 'Entrance fees', 'Traditional tea'],
    not_included: ['Personal expenses', 'Tips'],
    featured: true,
    rating: 4.9,
    review_count: 156
  },
  {
    id: '2',
    name: 'Gobustan & Mud Volcanoes Adventure',
    slug: 'gobustan-mud-volcanoes',
    description: 'Journey back in time at Gobustan National Park, home to over 6,000 rock paintings dating back 40,000 years. Then experience the otherworldly landscape of mud volcanoes, including the world\'s highest mud volcano.',
    short_description: 'Ancient petroglyphs and unique geological wonders just outside Baku.',
    price: 10,
    duration: '5 hours',
    difficulty: 'Easy',
    category: 'adventure',
    region: 'Absheron',
    image_url: '../img/portfolio/qobustan.jpg',
    gallery: ['../img/portfolio/qobustan.jpg'],
    highlights: ['6,000+ petroglyphs', 'Mud volcano fields', 'Gaval Dash musical stone', 'Archaeological museum'],
    included: ['Transportation', 'Guide', 'Museum tickets', 'Refreshments'],
    not_included: ['Personal expenses'],
    featured: true,
    rating: 4.8,
    review_count: 203
  },
  {
    id: '3',
    name: 'Sheki Cultural Journey',
    slug: 'sheki-cultural',
    description: 'Travel to the charming mountain town of Sheki, known for its UNESCO-listed Khan\'s Palace, traditional halva, and stunning mountain scenery. Experience authentic Azerbaijani hospitality in this historic Silk Road city.',
    short_description: 'UNESCO heritage, traditional crafts, and mountain scenery.',
    price: 20,
    duration: '1 day',
    difficulty: 'Moderate',
    category: 'cultural',
    region: 'Sheki',
    image_url: '../img/portfolio/sheki-1.jpg',
    gallery: ['../img/portfolio/sheki-1.jpg', '../img/portfolio/sheki-2.png'],
    highlights: ['Sheki Khan Palace', 'Karavansaray', 'Halva tasting', 'Craft workshops'],
    included: ['Transportation', 'Guide', 'Accommodation', 'Breakfast'],
    not_included: ['Lunch', 'Dinner', 'Personal expenses'],
    featured: true,
    rating: 4.9,
    review_count: 89
  },
  {
    id: '4',
    name: 'Gabala Mountain Escape',
    slug: 'gabala-mountain',
    description: 'Discover Azerbaijan\'s premier mountain destination. Gabala offers stunning natural beauty, from the Caucasus Mountains to pristine lakes. Visit ancient ruins, enjoy cable car rides, and experience thrilling activities.',
    short_description: 'Mountain adventures in the stunning Caucasus range.',
    price: 30,
    duration: '1-2 days',
    difficulty: 'Moderate',
    category: 'adventure',
    region: 'Gabala',
    image_url: '../img/portfolio/qebele-1.jpg',
    gallery: ['../img/portfolio/qebele-1.jpg'],
    highlights: ['Tufandag Ski Resort', 'Nohur Lake', 'Yeddi Gozel Waterfall', 'Cable car experience'],
    included: ['Transportation', 'Guide', 'Accommodation', 'Breakfast'],
    not_included: ['Activities', 'Meals'],
    featured: true,
    rating: 4.7,
    review_count: 124
  },
  {
    id: '5',
    name: 'Ateshgah Fire Temple & Yanar Dag',
    slug: 'ateshgah-yanar-dag',
    description: 'Visit the mysterious fire temple of Ateshgah, where natural gas has been burning for centuries. Then witness the eternal flames of Yanar Dag, where fire shoots from the ground in a spectacular natural phenomenon.',
    short_description: 'Ancient fire worship traditions and eternal flames.',
    price: 10,
    duration: '4 hours',
    difficulty: 'Easy',
    category: 'cultural',
    region: 'Absheron',
    image_url: '../img/portfolio/ateshgah-2.jpg',
    gallery: ['../img/portfolio/ateshgah-2.jpg', '../img/portfolio/ateshgah2.jpg'],
    highlights: ['Ateshgah Temple', 'Yanar Dag eternal fire', 'Zoroastrian history', 'Sunset views'],
    included: ['Transportation', 'Guide', 'Entrance fees'],
    not_included: ['Personal expenses'],
    featured: false,
    rating: 4.6,
    review_count: 167
  },
  {
    id: '6',
    name: 'Shamakhi Wine Region Tour',
    slug: 'shamakhi-wine',
    description: 'Explore Azerbaijan\'s oldest wine-producing region. Visit the historic Juma Mosque, tour vineyards, taste local wines at award-winning wineries, and stargaze at one of the largest astrophysical observatories in the region.',
    short_description: 'Wine tasting, ancient mosques, and stargazing.',
    price: 30,
    duration: '1 day',
    difficulty: 'Easy',
    category: 'cultural',
    region: 'Shamakhi',
    image_url: '../img/portfolio/shamakhi.jpg',
    gallery: ['../img/portfolio/shamakhi.jpg'],
    highlights: ['Juma Mosque (743 AD)', 'Wine tasting', 'Vineyard tours', 'Observatory visit'],
    included: ['Transportation', 'Guide', 'Wine tasting', 'Lunch'],
    not_included: ['Wine purchases'],
    featured: false,
    rating: 4.8,
    review_count: 98
  },
  {
    id: '7',
    name: 'Lahij Craft Village Experience',
    slug: 'lahij-craft-village',
    description: 'Step back in time in this ancient mountain village known for its master copper craftsmen. Wander through cobblestone streets, watch artisans at work, and experience traditional Azerbaijani village life.',
    short_description: 'Traditional craftsmanship in a mountain village.',
    price: 30,
    duration: '1 day',
    difficulty: 'Moderate',
    category: 'cultural',
    region: 'Ismayilli',
    image_url: '../img/portfolio/lahic-1.jpg',
    gallery: ['../img/portfolio/lahic-1.jpg'],
    highlights: ['Copper craftsmanship', 'Traditional architecture', 'Mountain views', 'Local bazaar'],
    included: ['Transportation', 'Guide', 'Accommodation', 'Breakfast'],
    not_included: ['Craft purchases'],
    featured: false,
    rating: 4.9,
    review_count: 72
  },
  {
    id: '8',
    name: 'Goygol Lake & Ganja Tour',
    slug: 'goygol-ganja',
    description: 'Visit Azerbaijan\'s first national park and its stunning emerald lake formed by an earthquake. Explore historic Ganja, the country\'s second-largest city, with its ancient monuments and vibrant culture.',
    short_description: 'Emerald lakes and ancient Silk Road history.',
    price: 35,
    duration: '1 day',
    difficulty: 'Moderate',
    category: 'nature',
    region: 'Ganja',
    image_url: '../img/portfolio/GoyGol.jpg',
    gallery: ['../img/portfolio/GoyGol.jpg'],
    highlights: ['Goygol Lake', 'Ganja city', 'Nizami Mausoleum', 'German heritage'],
    included: ['Transportation', 'Guide', 'Accommodation', 'Breakfast'],
    not_included: ['Meals'],
    featured: false,
    rating: 4.7,
    review_count: 54
  },
  {
    id: '9',
    name: 'Mountain Hiking Adventure',
    slug: 'mountain-hiking',
    description: 'Trek through the spectacular Caucasus Mountains with experienced guides. Choose from routes of varying difficulty, from gentle day hikes to multi-day expeditions. Experience pristine nature and breathtaking vistas.',
    short_description: 'Multi-day treks through the Caucasus Mountains.',
    price: 50,
    duration: '1-3 days',
    difficulty: 'Challenging',
    category: 'adventure',
    region: 'Caucasus',
    image_url: '../img/portfolio/Hiking.jpg',
    gallery: ['../img/portfolio/Hiking.jpg'],
    highlights: ['Caucasus peaks', 'Mountain villages', 'Wild camping', 'Local cuisine'],
    included: ['Guide', 'Equipment', 'Accommodation', 'Meals'],
    not_included: ['Personal gear'],
    featured: true,
    rating: 4.9,
    review_count: 45
  },
  {
    id: '10',
    name: 'Naftalan Health Retreat',
    slug: 'naftalan-health',
    description: 'Experience the unique therapeutic properties of Naftalan oil treatments. This centuries-old practice is believed to help with various ailments. Relax in premium spa facilities with expert medical supervision.',
    short_description: 'Unique therapeutic oil treatments and wellness.',
    price: 50,
    duration: '1-7 days',
    difficulty: 'Easy',
    category: 'nature',
    region: 'Naftalan',
    image_url: '../img/portfolio/naftalan-1.jpg',
    gallery: ['../img/portfolio/naftalan-1.jpg'],
    highlights: ['Oil baths', 'Spa treatments', 'Medical supervision', 'Relaxation'],
    included: ['Accommodation', 'Treatments', 'Meals', 'Medical consultation'],
    not_included: ['Personal expenses'],
    featured: false,
    rating: 4.6,
    review_count: 38
  },
  {
    id: '11',
    name: 'Baku Museums Day',
    slug: 'baku-museums',
    description: 'Discover Baku\'s rich cultural scene through its world-class museums. Visit the iconic Heydar Aliyev Center, the National Museum of History, the Carpet Museum, and more. Perfect for culture enthusiasts.',
    short_description: 'A journey through Azerbaijani history and art.',
    price: 0,
    duration: '1 day',
    difficulty: 'Easy',
    category: 'cultural',
    region: 'Baku',
    image_url: '../img/portfolio/museums-trip-2.jpg',
    gallery: ['../img/portfolio/museums-trip-2.jpg'],
    highlights: ['Heydar Aliyev Center', 'Carpet Museum', 'National Museum', 'Modern Art Museum'],
    included: ['Guide', 'Transportation'],
    not_included: ['Museum tickets', 'Meals'],
    featured: false,
    rating: 4.5,
    review_count: 89
  }
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Chidongqi',
    location: 'Singapore',
    content: 'Amazing experience! The team organized everything perfectly and showed us hidden gems we never would have found on our own.',
    rating: 5,
    tour_name: 'Baku Old City Walking Tour'
  },
  {
    id: '2',
    name: 'Asma',
    location: 'India',
    content: 'Professional service from start to finish. Our guide was knowledgeable and the itinerary was perfectly tailored to our interests.',
    rating: 5,
    tour_name: 'Sheki Cultural Journey'
  }
]

export const stats = [
  { label: 'Happy Travelers', value: '5,000+' },
  { label: 'Tours Completed', value: '2,500+' },
  { label: 'Countries Served', value: '45+' },
  { label: 'Years Experience', value: '5+' }
]

export const categories = [
  { id: 'cultural', slug: 'cultural', name: 'Cultural', icon: 'Landmark' },
  { id: 'adventure', slug: 'adventure', name: 'Adventure', icon: 'Mountain' },
  { id: 'nature', slug: 'nature', name: 'Nature', icon: 'Trees' },
]
